spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_hw5
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
logging:
  level:
    root: WARN
    Pegas.service.TaskService: ERROR
  file:
    name: log.txt
    path: /