spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %msg%n"
  file:
    name: ./log.txt